### ISSUE TITLE
Vizi.SpotLight looks for "position" on object, not transform

### ISSUE THREAD

**Issue by 190n** [tparisi/Vizi#7]
When I try to use a `Vizi.SpotLight` and pass in the `object` parameter, it seems to be looking for the object's position on the object itself, not its `transform` property.

I'm using this code:

``` js
light.addComponent(new Vizi.SpotLight({object: cube}));
```

I get this error (in the Safari debugger):
![TypeError: 'undefined' is not an object (evaluating 'a.object.position.clone')](https://cloud.githubusercontent.com/assets/7763597/3490693/f2f07bca-0577-11e4-8046-dfd71fe0f414.png)

Shouldn't it look for `position` on the object's `transform` property?

**Comment by tobscher** [comment]
Hi @fogcityben,

`Vizi.SpotLight` seems to be a wrapper for `THREE.SpotLight`. From what I can see the object param is for the use case where you have already built a `THREE.SpotLight`: https://github.com/tparisi/Vizi/blob/master/engine/src/lights/spotLight.js#L14-L19

Something like the following:

``` javascript
var parent = new Vizi.Object();
var spotLight = new THREE.SpotLight( 0xffffff );
var light = new Vizi.SpotLight({ object: spotLight });

parent.addComponent(light);
```

In this case calling `position` on the object you pass in (or the object Vizi creates for you) is correct.

**Comment by 190n** [comment]
Thanks a lot, @Tobscher! I'm closing the issue now.
